### PR TITLE
Limit importlib-metadata pin to Python 3.8

### PR DESCRIPTION
**Pull request by wshanks**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR primarily limits the importlib-metadata requirement to Python <= 3.8 so that it does not interfere with other packages like (tox) that require importlib-metadata >= 6. It also adds me as a maintainer.

### CODE REVIEW

**Comment by wshanks** [comment]
@conda-forge-admin, please rerender

**Comment by wshanks** [comment]
A new point release (0.23.3) was just published, but maybe we can sneak this in first.

**Comment by BastianZim** [comment]
Thank you! :)

**Comment by BastianZim** [comment]
Unfortunately not, the whole thing will be restarted. 
can you just push an empty commit?

**Comment by wshanks** [comment]
Huh, well, it took almost three hours but that last build did eventually complete successfully on its own.

**Pull request merged**
